import { createClient } from "@supabase/supabase-js";
import { randomUUID } from "node:crypto";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error("Gagal mendapatkan URL / KEY Supabase dari .env.local!");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Disamakan persis dengan di lib/types.ts
const ROLE_MATRIX = {
  1: ["lead_po", "cpo", "sa", "pm", "self"],
  2: ["lead_po", "cpo", "sa", "ui_ux", "pm", "self"],
  3: ["lead_po", "cpo", "sa", "qa", "pm", "self"],
  4: ["lead_po", "cpo", "sa", "ui_ux", "pm", "self"],
  5: ["lead_po", "cpo", "sa", "dev", "qa", "pm", "self"],
  6: ["lead_po", "cpo", "sa", "ui_ux", "dev", "qa", "pm", "self"],
  7: ["lead_po", "cpo", "sa", "ui_ux", "dev", "qa", "pm", "self"],
  8: ["lead_po", "cpo", "sa", "dev", "pm", "self"],
  9: ["lead_po", "cpo", "sa", "pm", "self"],
  10: ["lead_po", "cpo", "sa", "dev", "qa", "pm", "self"],
  11: ["lead_po", "cpo", "sa", "pm", "self"],
  12: ["lead_po", "cpo", "sa", "ui_ux", "dev", "qa", "pm", "self"],
  13: ["lead_po", "cpo", "sa", "dev", "qa", "pm", "self"],
  14: ["lead_po", "cpo", "sa", "pm", "self"],
  15: ["lead_po", "cpo", "sa", "ui_ux", "pm", "self"],
};

async function seedData() {
  console.log("Memulai proses seeding dummy data...");

  // 1. Dapatkan periode aktif
  let { data: periods } = await supabase.from("evaluation_periods").select("id").eq("is_active", true);
  
  let periodId;
  if (!periods || periods.length === 0) {
    console.log("Tidak ada periode aktif. Membuat satu (H1 2026)...");
    periodId = randomUUID();
    await supabase.from("evaluation_periods").insert({
      id: periodId,
      name: "H1 2026 Review Cycle",
      type: "post_test",
      start_date: "2026-06-01",
      end_date: "2026-06-30",
      is_active: true
    });
  } else {
    periodId = periods[0].id;
  }

  // 2. Buat target (Product Owners dan Lead PO)
  const po1 = { id: randomUUID(), name: "Budi (Lead PO)", squad: "Core Banking", is_active: true };
  const po2 = { id: randomUUID(), name: "Andi (Senior PO)", squad: "Lending", is_active: true };
  
  await supabase.from("product_owners").insert([po1, po2]);
  console.log("Telah membuat user: " + po1.name + " dan " + po2.name);

  // 3. Helper insert form
  const generateResponse = async (targetUserId, roleName, isOverconfident) => {
    const responseId = randomUUID();
    await supabase.from("responses").insert({
      id: responseId,
      period_id: periodId,
      po_id: targetUserId,
      rater_role: roleName,
      submitted_at: new Date().toISOString(),
      qualitative_note: `Generated by dummy bot for role: ${roleName}`
    });

    const scoresToInsert = [];
    for (let indicatorId = 1; indicatorId <= 15; indicatorId++) {
      const allowedRoles = ROLE_MATRIX[indicatorId];
      if (allowedRoles.includes(roleName)) {
        // Base score
        let score = 5; 
        
        // Buat jarak Gap
        if (roleName === "self") {
            score = isOverconfident ? 7 : 5; // Self score tinggi sekali (Overconfident) -> Ciptakan Critical GAP
        } else if (roleName === "cpo" || roleName === "lead_po") {
            score = isOverconfident ? 2 : 5; // Atasan memberi sangat pelit!
        } else {
            score = isOverconfident ? 3 : 5; // Tim memberi pelit
        }

        // Variasi pelengkap random 0.5 poin
        score = Math.max(1, Math.min(7, score));

        scoresToInsert.push({
          id: randomUUID(),
          response_id: responseId,
          indicator_id: indicatorId,
          score: score,
          is_na: false
        });
      } else {
         // Bypass (is_na=true)
         scoresToInsert.push({
            id: randomUUID(),
            response_id: responseId,
            indicator_id: indicatorId,
            score: 0,
            is_na: true
          });
      }
    }
    
    await supabase.from("scores").insert(scoresToInsert);
  };

  // 4. Eksekusi Penilaian Budi (Lead PO)
  // Budi memiliki ego tinggi (Overconfident). Dia dinilai oleh CPO.
  console.log("Generating Budi (Lead PO) forms...");
  await generateResponse(po1.id, "self", true); // Budi beri diri sendiri = 7
  await generateResponse(po1.id, "cpo", true);  // CPO beri nilai jelek = 2
  await generateResponse(po1.id, "sa", true);   // Peers beri nilai jelek
  await generateResponse(po1.id, "dev", true);
  await generateResponse(po1.id, "qa", true);

  // 5. Eksekusi Penilaian Andi (PO Biasa)
  // Andi punya kinerja selaras yang moderat. Dia dinilai oleh Lead PO.
  console.log("Generating Andi (Senior PO) forms...");
  await generateResponse(po2.id, "self", false);    // Andi konsisten dgn tim
  await generateResponse(po2.id, "lead_po", false); // Atasan (Mungkin si Budi) menilainya fair
  await generateResponse(po2.id, "ui_ux", false);
  await generateResponse(po2.id, "pm", false);
  await generateResponse(po2.id, "sa", false);

  console.log("\n======================");
  console.log("✅ Seeding selesai secara paripurna!");
  console.log("Silahkan cek Menu Dasbor Overview.");
}

seedData().catch(console.error);
